services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hocuspocus-v2.13.0-memory-leak-test:latest
    ports:
      - '0.0.0.0:80:80'
      - '127.0.0.1:9229:9229'
    command: node --inspect=0.0.0.0:9229 index.js
  redis:
    image: redis:7.2.3